name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    # - name: Run Tests
    #   run: npm test

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/ecommerce-api:latest
          ${{ secrets.DOCKER_HUB_USERNAME }}/ecommerce-api:${{ github.sha }}

    - name: Deploy to Render
      uses: render/render-action@v1
      with:
        api_key: ${{ secrets.RENDER_API_KEY }}
        service_name: ecommerce-api
        service_command: npm start
        service_port: 3000
        service_environment:
          - key: NODE_ENV
            value: production
          - key: PORT
            value: 3000
          - key: DATABASE_URL
            value: ${{ secrets.DATABASE_URL }}
          - key: JWT_SECRET
            value: ${{ secrets.JWT_SECRET }}
